[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_todo_list = "7FdoTRNSdgya71wk4h3ZSf4dtuiW7ZJozSG3RBR8sxQR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/solana/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
