[features]
seeds = false
skip-lint = false
[programs.devnet]
todo_list_app = "BqQB3NXmzg6uTvXZYnJCCuEPUwyMd5quMTM69Ze28v8u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/solana/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
